name: Build LiquidMorph tweak

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build .deb and Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot rsync curl git perl dpkg-dev bzip2 zstd unzip

      - name: Install Theos
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          git clone --recursive https://github.com/theos/theos.git "$THEOS"
          
          # Tải SDK chuẩn từ Theos
          mkdir -p "$THEOS/sdks"
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip -q master.zip
          mv sdks-master/*.sdk "$THEOS/sdks/"
          rm -rf master.zip sdks-master

      - name: Build package
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          export PATH="$THEOS/bin:$PATH"
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Make Repository Files for Sileo & Find Deb
        run: |
          mkdir -p public/debs
          
          find . -maxdepth 2 -name "*.deb" ! -path "./public/*" -exec cp {} public/debs/ \;
          
          cd public
          dpkg-scanpackages -m debs /dev/null > Packages
          bzip2 -9 -c Packages > Packages.bz2
          zstd -c Packages > Packages.zst
          
          cat << 'EOF' > Release
          Origin: LiquidMorph Repo
          Label: LiquidMorph Repo
          Suite: stable
          Version: 1.0
          Codename: ios
          Architectures: iphoneos-arm64
          Components: main
          Description: Repository for LiquidMorph Tweak
          EOF
          cd ..

      - name: Upload Repository Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository
          path: public/
